require File.expand_path('../fantasy-irc/irc', __FILE__)
require File.expand_path('../fantasy-irc/events', __FILE__)
require File.expand_path('../fantasy-irc/plugins', __FILE__)
require File.expand_path('../fantasy-irc/rooms', __FILE__)
require File.expand_path('../fantasy-irc/users', __FILE__)
